CREATE TABLE system_guard(id TINYINT UNSIGNED PRIMARY KEY,recovery_freeze BOOLEAN NOT NULL DEFAULT FALSE,authentication_blocked_until TIMESTAMP(6),reason VARCHAR(500),version BIGINT UNSIGNED NOT NULL DEFAULT 1,updated_by BINARY(16),updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6));
INSERT INTO system_guard(id) VALUES(1);
