CREATE TABLE schema_migrations (
  version BIGINT UNSIGNED PRIMARY KEY,
  applied_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;

CREATE TABLE departments (
  id BINARY(16) PRIMARY KEY, code VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(128) NOT NULL,
  status ENUM('ACTIVE','DISABLED') NOT NULL DEFAULT 'ACTIVE', version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
CREATE TABLE user_accounts (
  id BINARY(16) PRIMARY KEY, username VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
  display_name VARCHAR(128) NOT NULL, password_hash VARCHAR(255), status ENUM('PENDING_ACTIVATION','MFA_BIND_REQUIRED','ACTIVE','MFA_REBIND_REQUIRED','DISABLED') NOT NULL,
  mfa_state ENUM('UNBOUND','PENDING','ACTIVE','RESET_PENDING') NOT NULL DEFAULT 'UNBOUND', mfa_secret_ciphertext VARBINARY(1024), mfa_last_used_step BIGINT,
  session_version BIGINT UNSIGNED NOT NULL DEFAULT 1, password_changed_at TIMESTAMP(6) NULL, last_login_at TIMESTAMP(6) NULL,
  version BIGINT UNSIGNED NOT NULL DEFAULT 1, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
CREATE TABLE org_groups (
  id BINARY(16) PRIMARY KEY, department_id BINARY(16) NOT NULL, code VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(128) NOT NULL,
  status ENUM('ACTIVE','DISABLED') NOT NULL DEFAULT 'ACTIVE', version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_groups_department FOREIGN KEY (department_id) REFERENCES departments(id)
) ENGINE=InnoDB;
CREATE TABLE group_memberships (
  group_id BINARY(16) NOT NULL, user_id BINARY(16) NOT NULL, is_manager BOOLEAN NOT NULL DEFAULT FALSE, priority SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  valid_from TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), valid_until TIMESTAMP(6) NULL, PRIMARY KEY(group_id,user_id),
  CONSTRAINT fk_membership_group FOREIGN KEY(group_id) REFERENCES org_groups(id), CONSTRAINT fk_membership_user FOREIGN KEY(user_id) REFERENCES user_accounts(id)
) ENGINE=InnoDB;
CREATE TABLE roles (id BINARY(16) PRIMARY KEY, code VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(128) NOT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)) ENGINE=InnoDB;
CREATE TABLE role_permissions (role_id BINARY(16) NOT NULL, permission VARCHAR(128) NOT NULL, PRIMARY KEY(role_id,permission), CONSTRAINT fk_permission_role FOREIGN KEY(role_id) REFERENCES roles(id)) ENGINE=InnoDB;
CREATE TABLE user_role_assignments (
  id BINARY(16) PRIMARY KEY, user_id BINARY(16) NOT NULL, role_id BINARY(16) NOT NULL, scope_type ENUM('GLOBAL','DEPARTMENT','GROUP') NOT NULL, scope_id BINARY(16),
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uk_user_role_scope(user_id,role_id,scope_type,scope_id),
  CONSTRAINT fk_assignment_user FOREIGN KEY(user_id) REFERENCES user_accounts(id), CONSTRAINT fk_assignment_role FOREIGN KEY(role_id) REFERENCES roles(id)
) ENGINE=InnoDB;
CREATE TABLE activation_tokens (id BINARY(16) PRIMARY KEY, user_id BINARY(16) NOT NULL, token_hash BINARY(32) NOT NULL UNIQUE, purpose ENUM('ACTIVATE','MFA_REBIND') NOT NULL, expires_at TIMESTAMP(6) NOT NULL, consumed_at TIMESTAMP(6), attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT fk_activation_user FOREIGN KEY(user_id) REFERENCES user_accounts(id)) ENGINE=InnoDB;
CREATE TABLE login_challenges (id BINARY(16) PRIMARY KEY, user_id BINARY(16) NOT NULL, token_hash BINARY(32) NOT NULL UNIQUE, portal_zone ENUM('OFFICE','PRODUCTION','ADMIN') NOT NULL, browser_binding BINARY(32) NOT NULL, attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0, expires_at TIMESTAMP(6) NOT NULL, consumed_at TIMESTAMP(6), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT fk_challenge_user FOREIGN KEY(user_id) REFERENCES user_accounts(id), INDEX ix_challenge_expiry(expires_at)) ENGINE=InnoDB;
CREATE TABLE sessions (id BINARY(16) PRIMARY KEY, user_id BINARY(16) NOT NULL, token_hash BINARY(32) NOT NULL UNIQUE, portal_zone ENUM('OFFICE','PRODUCTION','ADMIN') NOT NULL, session_version BIGINT UNSIGNED NOT NULL, mfa_verified_at TIMESTAMP(6) NOT NULL, last_seen_at TIMESTAMP(6) NOT NULL, expires_at TIMESTAMP(6) NOT NULL, revoked_at TIMESTAMP(6), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT fk_session_user FOREIGN KEY(user_id) REFERENCES user_accounts(id), INDEX ix_session_user(user_id,revoked_at), INDEX ix_session_expiry(expires_at)) ENGINE=InnoDB;

CREATE TABLE workflow_definitions (id BINARY(16) PRIMARY KEY, name VARCHAR(128) NOT NULL, status ENUM('DRAFT','PUBLISHED','DISABLED') NOT NULL, scope_json JSON NOT NULL, current_version_id BINARY(16), version BIGINT UNSIGNED NOT NULL DEFAULT 1, created_by BINARY(16) NOT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB;
CREATE TABLE workflow_versions (id BINARY(16) PRIMARY KEY, definition_id BINARY(16) NOT NULL, version_number INT UNSIGNED NOT NULL, graph_json JSON NOT NULL, graph_sha256 BINARY(32) NOT NULL, status ENUM('DRAFT','PUBLISHED','RETIRED') NOT NULL, published_by BINARY(16), published_at TIMESTAMP(6), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uk_workflow_version(definition_id,version_number), CONSTRAINT fk_wfv_definition FOREIGN KEY(definition_id) REFERENCES workflow_definitions(id)) ENGINE=InnoDB;
ALTER TABLE workflow_definitions ADD CONSTRAINT fk_wfd_current FOREIGN KEY(current_version_id) REFERENCES workflow_versions(id);
CREATE TABLE exchange_requests (
  id BINARY(16) PRIMARY KEY, request_no VARCHAR(32) NOT NULL UNIQUE, requester_id BINARY(16) NOT NULL, group_id BINARY(16) NOT NULL,
  direction ENUM('PROD_TO_OFFICE','OFFICE_TO_PROD') NOT NULL, classification ENUM('INTERNAL','SENSITIVE','HIGH') NOT NULL,
  purpose TEXT NOT NULL, business_system_id BINARY(16), external_ticket VARCHAR(128), status ENUM('DRAFT','CHECKING','REJECTED_CHECK','PENDING_APPROVAL','APPROVED','COPYING','READY','PARTIALLY_DELIVERED','DELIVERED','REJECTED','CANCELLED','EXPIRED','REVOKED','QUARANTINED','BLOCKED') NOT NULL,
  workflow_version_id BINARY(16), frozen_snapshot JSON, file_count SMALLINT UNSIGNED NOT NULL DEFAULT 0, total_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  expires_at TIMESTAMP(6), published_at TIMESTAMP(6), version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_request_user FOREIGN KEY(requester_id) REFERENCES user_accounts(id), CONSTRAINT fk_request_group FOREIGN KEY(group_id) REFERENCES org_groups(id), CONSTRAINT fk_request_workflow FOREIGN KEY(workflow_version_id) REFERENCES workflow_versions(id),
  INDEX ix_request_owner(requester_id,created_at), INDEX ix_request_status(status,updated_at)
) ENGINE=InnoDB;
CREATE TABLE request_files (
  id BINARY(16) PRIMARY KEY, request_id BINARY(16) NOT NULL, original_name VARCHAR(512) NOT NULL, object_key VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_storage_revision_id BINARY(16), source_bucket VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin, source_version_id VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin, source_sha256 BINARY(32), size_bytes BIGINT UNSIGNED NOT NULL,
  target_storage_revision_id BINARY(16), target_bucket VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin, target_version_id VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin, target_sha256 BINARY(32),
  status ENUM('RESERVED','UPLOADING','UPLOADED','CHECKING','CHECK_PASSED','CHECK_FAILED','COPYING','COPIED','READY','QUARANTINED','DELETED') NOT NULL,
  check_report JSON, antivirus_status ENUM('NOT_REQUIRED','PENDING','PASSED','DETECTED','ERROR','SKIPPED_DISABLED') NOT NULL DEFAULT 'SKIPPED_DISABLED',
  version BIGINT UNSIGNED NOT NULL DEFAULT 1, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_source_object(source_storage_revision_id,source_bucket,object_key,source_version_id), CONSTRAINT fk_file_request FOREIGN KEY(request_id) REFERENCES exchange_requests(id), INDEX ix_file_request(request_id,status)
) ENGINE=InnoDB;
CREATE TABLE workflow_instances (id BINARY(16) PRIMARY KEY, request_id BINARY(16) NOT NULL UNIQUE, workflow_version_id BINARY(16) NOT NULL, frozen_graph JSON NOT NULL, status ENUM('RUNNING','APPROVED','REJECTED','CANCELLED','BLOCKED','EXPIRED') NOT NULL, current_node_id VARCHAR(64), version BIGINT UNSIGNED NOT NULL DEFAULT 1, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), completed_at TIMESTAMP(6), CONSTRAINT fk_instance_request FOREIGN KEY(request_id) REFERENCES exchange_requests(id), CONSTRAINT fk_instance_version FOREIGN KEY(workflow_version_id) REFERENCES workflow_versions(id)) ENGINE=InnoDB;
CREATE TABLE workflow_tasks (id BINARY(16) PRIMARY KEY, instance_id BINARY(16) NOT NULL, node_id VARCHAR(64) NOT NULL, assignee_id BINARY(16) NOT NULL, status ENUM('WAITING','PENDING','PAUSED','APPROVED','REJECTED','CANCELLED') NOT NULL, allow_admin_act_on_behalf BOOLEAN NOT NULL DEFAULT TRUE, due_at TIMESTAMP(6), version BIGINT UNSIGNED NOT NULL DEFAULT 1, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), decided_at TIMESTAMP(6), CONSTRAINT fk_task_instance FOREIGN KEY(instance_id) REFERENCES workflow_instances(id), CONSTRAINT fk_task_assignee FOREIGN KEY(assignee_id) REFERENCES user_accounts(id), INDEX ix_task_assignee(assignee_id,status,due_at)) ENGINE=InnoDB;
CREATE TABLE workflow_actions (id BINARY(16) PRIMARY KEY, task_id BINARY(16) NOT NULL, actor_id BINARY(16) NOT NULL, original_assignee_id BINARY(16) NOT NULL, decision ENUM('APPROVE','REJECT') NOT NULL, comment TEXT, acting_mode ENUM('SELF','ADMIN_ON_BEHALF') NOT NULL, delegation_reason VARCHAR(500), permission_scope_snapshot JSON, mfa_verified_at TIMESTAMP(6) NOT NULL, idempotency_key VARCHAR(128) NOT NULL, before_state JSON NOT NULL, after_state JSON NOT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uk_action_idempotency(actor_id,idempotency_key), CONSTRAINT fk_action_task FOREIGN KEY(task_id) REFERENCES workflow_tasks(id), CONSTRAINT fk_action_actor FOREIGN KEY(actor_id) REFERENCES user_accounts(id)) ENGINE=InnoDB;

CREATE TABLE jobs (id BINARY(16) PRIMARY KEY, type VARCHAR(64) NOT NULL, dedupe_key VARCHAR(191) NOT NULL UNIQUE, payload JSON NOT NULL, status ENUM('PENDING','RUNNING','SUCCEEDED','FAILED','DEAD') NOT NULL, available_at TIMESTAMP(6) NOT NULL, lease_holder VARCHAR(128), lease_token BIGINT UNSIGNED NOT NULL DEFAULT 0, lease_expires_at TIMESTAMP(6), attempts INT UNSIGNED NOT NULL DEFAULT 0, last_error_code VARCHAR(64), last_error_detail VARCHAR(1000), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX ix_job_claim(status,available_at,lease_expires_at)) ENGINE=InnoDB;
CREATE TABLE resource_slots (kind ENUM('UPLOAD','DOWNLOAD','COPY') NOT NULL, slot_no SMALLINT UNSIGNED NOT NULL, holder_id BINARY(16), fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0, lease_expires_at TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY(kind,slot_no), INDEX ix_slot_lease(kind,lease_expires_at)) ENGINE=InnoDB;
CREATE TABLE download_grants (id BINARY(16) PRIMARY KEY, request_id BINARY(16) NOT NULL, file_id BINARY(16) NOT NULL, user_id BINARY(16) NOT NULL, session_id BINARY(16) NOT NULL, portal_zone ENUM('OFFICE','PRODUCTION') NOT NULL, token_hash BINARY(32) NOT NULL UNIQUE, status ENUM('ISSUED','STARTED','COMPLETED','INTERRUPTED','EXPIRED','REVOKED') NOT NULL, expires_at TIMESTAMP(6) NOT NULL, started_at TIMESTAMP(6), completed_at TIMESTAMP(6), bytes_sent BIGINT UNSIGNED NOT NULL DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), CONSTRAINT fk_grant_request FOREIGN KEY(request_id) REFERENCES exchange_requests(id), CONSTRAINT fk_grant_file FOREIGN KEY(file_id) REFERENCES request_files(id), INDEX ix_grant_expiry(status,expires_at)) ENGINE=InnoDB;
CREATE TABLE audit_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, event_id BINARY(16) NOT NULL UNIQUE, occurred_at TIMESTAMP(6) NOT NULL, actor_id BINARY(16), action VARCHAR(128) NOT NULL, result ENUM('SUCCESS','DENIED','FAILED') NOT NULL, request_id BINARY(16), resource_type VARCHAR(64), resource_id BINARY(16), portal_zone ENUM('OFFICE','PRODUCTION','ADMIN'), trace_id VARCHAR(64), details JSON NOT NULL, previous_hash BINARY(32), event_hash BINARY(32) NOT NULL, INDEX ix_audit_time(occurred_at,id), INDEX ix_audit_actor(actor_id,occurred_at), INDEX ix_audit_request(request_id,occurred_at)) ENGINE=InnoDB;
CREATE TABLE notification_deliveries (id BINARY(16) PRIMARY KEY, event_id BINARY(16) NOT NULL, rule_id BINARY(16) NOT NULL, group_binding_id BINARY(16) NOT NULL, occurrence_no INT UNSIGNED NOT NULL, status ENUM('PENDING','SENDING','ACCEPTED','FAILED','UNKNOWN','SUPPRESSED') NOT NULL, mentioned_users JSON NOT NULL, proxy_revision_id BINARY(16), attempts INT UNSIGNED NOT NULL DEFAULT 0, available_at TIMESTAMP(6) NOT NULL, last_error_code VARCHAR(64), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE KEY uk_delivery(event_id,rule_id,group_binding_id,occurrence_no), INDEX ix_delivery_queue(status,available_at)) ENGINE=InnoDB;
CREATE TABLE monitoring_tokens (id BINARY(16) PRIMARY KEY, name VARCHAR(128) NOT NULL, token_hash BINARY(32) NOT NULL UNIQUE, scope VARCHAR(64) NOT NULL DEFAULT 'monitoring:read', allowed_cidrs JSON NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, expires_at TIMESTAMP(6), last_used_at TIMESTAMP(6), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), revoked_at TIMESTAMP(6)) ENGINE=InnoDB;
CREATE TABLE monitoring_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BINARY(16) NOT NULL UNIQUE, dedupe_key VARCHAR(191) NOT NULL UNIQUE, event_type VARCHAR(64) NOT NULL, user_id BINARY(16), direction ENUM('PROD_TO_OFFICE','OFFICE_TO_PROD'), bytes_delta BIGINT UNSIGNED NOT NULL DEFAULT 0, occurred_at TIMESTAMP(6) NOT NULL, source_id BINARY(16), INDEX ix_monitor_event(occurred_at,event_type), INDEX ix_monitor_user(user_id,occurred_at)) ENGINE=InnoDB;
CREATE TABLE transfer_progress (transfer_id BINARY(16) NOT NULL, sequence BIGINT UNSIGNED NOT NULL, cumulative_bytes BIGINT UNSIGNED NOT NULL, reported_at TIMESTAMP(6) NOT NULL, PRIMARY KEY(transfer_id,sequence), INDEX ix_transfer_reported(reported_at)) ENGINE=InnoDB;
CREATE TABLE monitoring_snapshots (scope VARCHAR(64) PRIMARY KEY, schema_version INT UNSIGNED NOT NULL, window_end TIMESTAMP(6) NOT NULL, valid BOOLEAN NOT NULL, metrics JSON NOT NULL, cursor_value BIGINT UNSIGNED NOT NULL, updated_at TIMESTAMP(6) NOT NULL) ENGINE=InnoDB;
CREATE TABLE security_incidents (id BINARY(16) PRIMARY KEY, fingerprint BINARY(32) NOT NULL UNIQUE, category ENUM('POLICY_BREACH','INTEGRITY') NOT NULL, severity ENUM('HIGH','CRITICAL') NOT NULL, status ENUM('OPEN','ACKNOWLEDGED','CLOSED') NOT NULL, first_seen_at TIMESTAMP(6) NOT NULL, last_seen_at TIMESTAMP(6) NOT NULL, request_id BINARY(16), acknowledged_by BINARY(16), acknowledged_at TIMESTAMP(6), closed_by BINARY(16), closed_at TIMESTAMP(6), resolution TEXT, version BIGINT UNSIGNED NOT NULL DEFAULT 1, INDEX ix_incident_status(status,category)) ENGINE=InnoDB;

INSERT INTO resource_slots(kind,slot_no) VALUES ('UPLOAD',1),('UPLOAD',2),('UPLOAD',3),('UPLOAD',4),('UPLOAD',5),('UPLOAD',6),('DOWNLOAD',1),('DOWNLOAD',2),('DOWNLOAD',3),('DOWNLOAD',4),('DOWNLOAD',5),('DOWNLOAD',6),('COPY',1),('COPY',2);
INSERT INTO schema_migrations(version) VALUES (1);
